### ISSUE TITLE
Help wanted: How can I extract the JIRA ticket number from Git branch name

### ISSUE THREAD

**Issue by Abdul-Hannan** [bitrise-steplib/steps-post-jira-comment-with-build-details#4]
We have a convention that branch name should start with JIRA ticket number

so if Jira ticket is : https://xyz.atlassian.net/browse/PP-4045
so branch name will start with PP-4045

Jira issue key is a required input for this step. How can I enter this value dynamically in my case?

**Comment by BirmacherAkos** [comment]
Hi @Abdul-Hannan !

If you put `$BITRISE_GIT_BRANCH` in the `Jira issue keys` input it should work.

I'm closing this issue. 
If you have more questions please open a new thread on  [discuss-questions](https://discuss.bitrise.io/c/question-answer).
